bootiful?
stamford-syntax-workshop/stamford-coin pull request #1
Opened 2024-01-20 22:20 UTC by NayHtetKyaw

2024-01-21 15:46 UTC, Lxkas requested changes

2024-01-21 15:46 UTC, Lxkas commented on src/App.jsx
> +					</div>
```suggestion
						<Flex direction="column" gap="4">
							<Text align="center" size="5" color="green">Success!</Text>
							{data.coins.map((coin) => (
								<Link 
									key={"coin_" + coin.uuid} 
									to={`/coins/${coin.uuid}`} 
									className="p-1 rounded hover:bg-blue-500/50 "
								>
									<Text>
										<Strong>{coin.name}</Strong> ({coin.symbol})
									</Text>
								</Link>
							))}
						</Flex>
```

2024-01-21 15:46 UTC, Lxkas commented on src/components/ApplicationHeader.jsx
>  		</Container>
```suggestion
		<Container className="mb-4 uppercase">
			<Link to="/" className="hover:font-bold">
				Home
			</Link>
		</Container>
```

2024-01-21 15:46 UTC, Lxkas commented on src/components/ApplicationHeader.jsx
>  		</Container>
Honestly it's pretty ugly 'cuz of the body's padding and the color lol

2024-01-21 15:46 UTC, Lxkas commented on src/App.jsx
> +					</div>
Let's just make the whole page scrollable, there's really no reason to limit it into a scrollarea, and if there was, we'd use the [Scroll Area](https://www.radix-ui.com/themes/docs/components/scroll-area) component

2024-01-21 15:46 UTC, Lxkas commented on src/index.css
> +@import 'tailwindcss/utilities';
Is there a specific reason for this? Because [according to the docs](https://tailwindcss.com/docs/guides/vite) we'd do it with the `@tailwind` directive

2024-01-21 15:46 UTC, Lxkas commented on src/pages/Coins.jsx
> +	);
...? What? This can be a component, and also using string interp would be better, or even using [cslx](https://www.npmjs.com/package/clsx) or [tailwindmerge](https://www.npmjs.com/package/tailwind-merge)

2024-01-21 15:46 UTC, Lxkas commented on src/pages/Coins.jsx
> +	);
Also, these should be defined outside the component? I have so many questions

2024-01-21 15:46 UTC, Lxkas commented on src/pages/Coins.jsx
> +				UUID : {uuid}{" "}
Why is there a trailing space here?

2024-01-21 15:46 UTC, Lxkas commented on src/pages/FourOhFour.jsx
> +			<Text align="center" className="text-2xl text-gray-700">Not Found!</Text>
Avoid darkish gray text on a dark gray background

2024-01-21 15:46 UTC, Lxkas commented on src/pages/FourOhFour.jsx
> +			<Text align="center" color="red" size="7">Uh Oh! Stinky!</Text>
tbh this red is just.. not doing it for me

2024-01-21 15:46 UTC, Lxkas commented on src/App.jsx
> +			<Flex direction="column" gap="4" >
Trailing space, why? Does the formatter not catch this? Idk

2024-01-23 05:46 UTC, NayHtetKyaw commented on src/components/ApplicationHeader.jsx
>  		</Container>
true, i didn't like it either. xD

2024-01-23 05:49 UTC, NayHtetKyaw commented on src/App.jsx
> +			<Flex direction="column" gap="4" >
probably the format, i didn't do it on purpose.

2024-01-23 05:50 UTC, NayHtetKyaw commented on src/index.css
> +@import 'tailwindcss/utilities';
bcos, @taildwind didn't work on my manchine. So i tried to fix it.

2024-01-23 06:22 UTC, Lxkas commented on src/index.css
> +@import 'tailwindcss/utilities';
didn't work as in an error or was it a warning? Keep in mind ESLint might show warnings as errors, even though they're completely benign

2024-01-23 06:49 UTC, chinathaip commented on src/index.css
> +@import 'tailwindcss/utilities';
so weird, yesterday I discussed with Ana about the `@tailwind` didn't work on my machine too

But it works now though...  can you try again and let me know? @NayHtetKyaw

2024-01-24 11:43 UTC, closed without merging